### ISSUE TITLE
Associates .asmg file extension with itself without any options to disable it.

### ISSUE THREAD

**Issue by Yarpopcat08** [DosX-dev/ASM-Guard#1]
Basically the name tells it all. I don't want the extension to be associated with anything. Maybe add the button to not associate it with the program like the one with context menu?

**Comment by DosX-dev** [comment]
Hello! I will consider disabling this feature. For now, you can only unassociate an extension through the registry. I apologize for the inconvenience!

**Comment by Yarpopcat08** [comment]
Thank you!
